spring.application.name=assignationVoiture

# PostgreSQL Railway (PUBLIC URL)
spring.datasource.url=jdbc:postgresql://maglev.proxy.rlwy.net:47176/railway
spring.datasource.username=postgres
spring.datasource.password=WmIPfLVyvjiumAmELYevLpvMbUgYHgQD
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080
