spring.application.name=assignationVoiture

# PostgreSQL (Railway)
 
SPRING_DATASOURCE_URL=jdbc:postgresql://postgres.railway.internal:5432/railway
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=UpTsWiuCcoDGchThbfucimMnDrSBEefJ
SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

 

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=${PORT:8080}
